### ISSUE TITLE
Repo in die IT4Kids Organisation umziehen + auf der Homepage verlinken

### ISSUE THREAD

**Issue by stes** [IT4Kids/it4kids#9]
Das wird gemacht sobald der Klickdummy im master Branch vorliegt. #5 und #7 sollten also vorher erledigt werden.

**Comment by Redix** [comment]
Sollte eventuell zeitnah gemacht werden, da auch alle Issues kopiert werden müssen. (Falls es dafür keine extra Funktion gibt)

**Comment by Redix** [comment]
@stes bitte einmal umziehen. Sollte schnell gehen:
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by Redix** [comment]
@stes nochmal die Bitte:
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by stes** [comment]
done. @Redix , du bist jetzt auch Admin und kannst die neuen hinzufügen!
